#xhost +local:

services:
  ros2_gazebo:
    build: .
    privileged: true
    entrypoint: "sleep 3333d"
    network_mode: host  
    environment:
      - DISPLAY
    volumes:
      - ./data:/root/data
      - /dev/input:/dev/input
